# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AskFollowUpQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AskFollowUpQuestion", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def DecodeQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecodeQuestion", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[str], __result__)

    def EvaluateInformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InformationEvaluation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateInformation", llm_response=llm_response, mode="request")
        return typing.cast(types.InformationEvaluation, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def ExtractSymptoms(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractedSymptoms:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractSymptoms", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractedSymptoms, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AskFollowUpQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AskFollowUpQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def DecodeQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecodeQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[str], __result__)

    def EvaluateInformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InformationEvaluation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateInformation", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InformationEvaluation, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def ExtractSymptoms(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractedSymptoms:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractSymptoms", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractedSymptoms, __result__)

    