# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class ExtractedSymptoms(BaseModel):
    symptoms: typing.List[str] = Field(description='A list of symptoms or medical issues described by the user.')

class InformationEvaluation(BaseModel):
    has_enough_info: typing.Optional[bool] = Field(default=None, description='True if the user has provided sufficient medical details (symptoms, duration, context) to begin research, or false if more clarifying questions need to be asked.')
    confidence: typing.Optional[float] = Field(default=None, description='A value between 0.0 and 1.0 indicating how confident you are in this assessment.')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
